-- ============================================================================
-- Analytics de Taverna — schema do banco (Supabase / Postgres)
--
-- Rode isto no Supabase → SQL Editor. É idempotente: pode rodar de novo sem
-- quebrar nada (usa IF NOT EXISTS / DROP POLICY IF EXISTS).
--
-- Responsáveis: Julia (define o que a API precisa) + Yasmin (banco/queries).
-- ============================================================================


-- ─────────────────────────────────────────────────────────────────────────────
-- 1. JOGADORES
--
-- A tabela já existe no projeto (o frontend insere nela em PersonagemCard.tsx).
-- Aqui a criamos se ainda não existir e ADICIONAMOS as colunas novas que o
-- sistema de batalha e o ranking precisam. Nenhuma coluna antiga é removida,
-- então nada do que já funciona quebra.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.jogadores (
  id           bigint generated by default as identity primary key,
  classe       text,
  forca        integer,
  inteligencia integer,
  agilidade    integer,
  resistencia  integer,
  carisma      integer,
  sabedoria    integer,
  caos         integer,
  foto_url     text,
  criado_em    timestamptz default now()
);

-- Identificação (o ranking precisa mostrar um nome).
alter table public.jogadores add column if not exists nome text;

-- Placar do ranking global (entregável 8).
alter table public.jogadores add column if not exists xp       integer not null default 0;
alter table public.jogadores add column if not exists vitorias integer not null default 0;
alter table public.jogadores add column if not exists derrotas integer not null default 0;
alter table public.jogadores add column if not exists empates  integer not null default 0;

-- As 10 dimensões brutas do quiz.
-- Por que guardar? Dois motivos:
--   1. A batalha usa "Estratégia" e "Criatividade", que são DIMENSÕES do quiz,
--      não atributos do card (o card tem força/agilidade/resistência/caos...).
--   2. O insight do dashboard previsto no PDF ("a maioria apresentou perfil
--      mais impulsivo do que estratégico") só é calculável com as dimensões.
alter table public.jogadores add column if not exists lideranca     integer;
alter table public.jogadores add column if not exists estrategia    integer;
alter table public.jogadores add column if not exists disciplina    integer;
alter table public.jogadores add column if not exists persistencia  integer;
alter table public.jogadores add column if not exists sociabilidade integer;
alter table public.jogadores add column if not exists empatia       integer;
alter table public.jogadores add column if not exists adaptabilidade integer;
alter table public.jogadores add column if not exists criatividade  integer;
alter table public.jogadores add column if not exists impulsividade integer;
alter table public.jogadores add column if not exists percepcao     integer;

-- Índices: o ranking ordena por XP o tempo todo; o pareamento filtra por XP.
create index if not exists jogadores_xp_idx        on public.jogadores (xp desc);
create index if not exists jogadores_criado_em_idx on public.jogadores (criado_em desc);
create index if not exists jogadores_classe_idx    on public.jogadores (classe);


-- ─────────────────────────────────────────────────────────────────────────────
-- 2. BATALHAS  (entregável 5 — registro da batalha)
--
-- Uma linha por batalha. Guardamos os VALORES usados no confronto, e não só o
-- vencedor: se o jogador ganhar XP depois, o histórico continua contando a
-- verdade sobre aquele momento.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.batalhas (
  id           bigint generated by default as identity primary key,

  jogador_a_id bigint not null references public.jogadores(id) on delete cascade,
  jogador_b_id bigint not null references public.jogadores(id) on delete cascade,

  -- Os atributos escolhidos pelo desafiante, separados por vírgula
  -- (ex.: 'forca,carisma,caos'). Linhas antigas guardam um atributo só.
  atributo     text   not null,

  -- PLACAR de rodadas (0..3) de cada lado.
  -- Nas linhas antigas: o valor do atributo único disputado.
  valor_a      integer not null,
  valor_b      integer not null,

  -- 'a' venceu | 'b' venceu | 'empate'
  resultado    text   not null check (resultado in ('a', 'b', 'empate')),

  -- NULL quando empate. Facilita "quantas vitórias o jogador X tem".
  vencedor_id  bigint references public.jogadores(id) on delete set null,

  xp_a         integer not null default 0,
  xp_b         integer not null default 0,

  criado_em    timestamptz default now(),

  -- Ninguém batalha contra si mesmo.
  constraint batalha_jogadores_distintos check (jogador_a_id <> jogador_b_id)
);

-- Detalhe das 3 rodadas. Cada item traz o atributo disputado (o mesmo dos dois
-- lados), os dois valores e quem venceu. NULL nas batalhas do formato antigo.
--
-- Por que jsonb e não 3 trios de colunas: o número de rodadas é regra de jogo,
-- não de banco. Se o formato virar 5 rodadas, nada aqui muda.
alter table public.batalhas add column if not exists rodadas jsonb;

create index if not exists batalhas_jogador_a_idx on public.batalhas (jogador_a_id);
create index if not exists batalhas_jogador_b_idx on public.batalhas (jogador_b_id);
create index if not exists batalhas_criado_em_idx on public.batalhas (criado_em desc);


-- ─────────────────────────────────────────────────────────────────────────────
-- 3. RLS (Row Level Security)
--
-- Contexto de segurança do projeto:
--   • O BACKEND (FastAPI na Render) usa a chave service_role, que ignora RLS.
--     Ou seja: as políticas abaixo NÃO afetam a API.
--   • O FRONTEND (Next na Vercel) usa a chave anon, que É limitada por RLS.
--
-- Por isso: leitura liberada para o anon (ranking/dashboard são públicos),
-- mas ESCRITA em `batalhas` e no placar só pelo backend. Isso impede alguém
-- de abrir o console do navegador e se dar 10.000 de XP.
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.jogadores enable row level security;
alter table public.batalhas  enable row level security;

-- jogadores: o frontend ainda insere o personagem direto (fluxo atual do card)
drop policy if exists "jogadores_insert_anon" on public.jogadores;
create policy "jogadores_insert_anon"
  on public.jogadores for insert
  to anon, authenticated
  with check (true);

drop policy if exists "jogadores_select_anon" on public.jogadores;
create policy "jogadores_select_anon"
  on public.jogadores for select
  to anon, authenticated
  using (true);

-- Sem policy de UPDATE para anon = o placar (xp/vitórias/derrotas) só muda
-- pela API. É de propósito.

-- batalhas: leitura pública (histórico/dashboard), escrita só pelo backend
drop policy if exists "batalhas_select_anon" on public.batalhas;
create policy "batalhas_select_anon"
  on public.batalhas for select
  to anon, authenticated
  using (true);


-- ─────────────────────────────────────────────────────────────────────────────
-- 4. INCREMENTO ATÔMICO DO PLACAR (opcional, mas recomendado)
--
-- Sem isto, a API precisa fazer "lê o XP → soma → grava". Se duas batalhas do
-- mesmo jogador terminarem no mesmo instante, uma sobrescreve a outra e um XP
-- se perde (isso se chama race condition / lost update).
--
-- Esta função faz a soma dentro do próprio Postgres, numa operação só.
-- A API chama via RPC e, se a função não existir, cai no modo lê-soma-grava.
-- ─────────────────────────────────────────────────────────────────────────────

create or replace function public.aplicar_resultado_batalha(
  p_jogador_id bigint,
  p_xp         integer,
  p_resultado  text          -- 'vitoria' | 'derrota' | 'empate'
)
returns public.jogadores
language plpgsql
security definer
set search_path = public
as $$
declare
  linha public.jogadores;
begin
  update public.jogadores
     set xp       = coalesce(xp, 0) + p_xp,
         vitorias = coalesce(vitorias, 0) + case when p_resultado = 'vitoria' then 1 else 0 end,
         derrotas = coalesce(derrotas, 0) + case when p_resultado = 'derrota' then 1 else 0 end,
         empates  = coalesce(empates,  0) + case when p_resultado = 'empate'  then 1 else 0 end
   where id = p_jogador_id
  returning * into linha;

  return linha;
end;
$$;
