import Image from "next/image";
import type { SVGProps, FC } from "react";
export type IllustratedIconProps = SVGProps<SVGSVGElement> & { size?: number | string; strokeWidth?: number | string };
export type LucideIcon = FC<IllustratedIconProps>;
function createIcon(index: number, extra = false): LucideIcon {
  return function IllustratedIcon({ size = 24, style, ...props }: IllustratedIconProps) {
    const row = Math.floor(index / 6);
    const boundaries = extra ? [0,100,200,300,400] : [0,124,217,307,403,492,600];
    const top = boundaries[row];
    const height = boundaries[row + 1] - top;
    const { className } = props;
    const cropWidth = 92;
    const cropHeight = height - 6;
    return <span className={`illustrated-icon ${className ?? ""}`} aria-hidden="true" style={{ display: "inline-block", position: "relative", overflow: "hidden", flexShrink: 0, verticalAlign: "middle", width: size, height: size, ...style }}>
      <Image src={extra ? "/icons/tavern-extra-loaded-v4.png" : "/icons/tavern-ui-loaded-v2.png"} alt="" width={1536} height={extra ? 1024 : 1536} unoptimized loading="eager" style={{ position: "absolute", width: `${600 / cropWidth * 100}%`, maxWidth: "none", height: `${(extra ? 400 : 600) / cropHeight * 100}%`, left: `${-((index % 6) * 100 + 4) / cropWidth * 100}%`, top: `${-(top + 3) / cropHeight * 100}%` }} />
    </span>;
  };
}
export const Swords = createIcon(0);
export const WandSparkles = createIcon(1);
export const ArrowDown = createIcon(2);
export const ChevronLeft = createIcon(3);
export const ChevronRight = createIcon(4);
export const Map = createIcon(5);
export const Castle = createIcon(6);
export const Trophy = createIcon(7);
export const BarChart3 = createIcon(8);
export const Feather = createIcon(9);
export const Camera = createIcon(10);
export const Brain = createIcon(11);
export const WalletCards = createIcon(12);
export const Smartphone = createIcon(13);
export const Target = createIcon(14);
export const DoorOpen = createIcon(15);
export const FlaskConical = createIcon(16);
export const Monitor = createIcon(17);
export const Cog = createIcon(18);
export const Bot = createIcon(19);
export const Ruler = createIcon(20);
export const Database = createIcon(21);
export const Dna = createIcon(22);
export const Globe = createIcon(23);
export const Gamepad2 = createIcon(24);
export const Users = createIcon(25);
export const UserRound = createIcon(26);
export const Check = createIcon(27);
export const Compass = createIcon(28);
export const Scroll = createIcon(29);
export const TriangleAlert = createIcon(30);
export const Route = createIcon(31);
export const Download = createIcon(32);
export const Share2 = createIcon(33);
export const Pause = createIcon(34);
export const Play = createIcon(35);
export const Crystal = createIcon(0, true);
export const Eye = createIcon(1, true);
export const BicepsFlexed = createIcon(2, true);
export const Spreadsheet = createIcon(3, true);
export const House = createIcon(4, true);
export const Coins = createIcon(5, true);
export const VenetianMask = createIcon(6, true);
export const Wrench = createIcon(7, true);
export const Pizza = createIcon(8, true);
export const Leaf = createIcon(9, true);
export const Broom = createIcon(10, true);
export const Headphones = createIcon(11, true);
export const Heart = createIcon(12, true);
export const Shield = createIcon(13, true);
export const Dog = createIcon(14, true);
export const Tornado = createIcon(15, true);
export const Owl = createIcon(16, true);
export const Flower = createIcon(17, true);
export const LinkedinMark = createIcon(18, true);
export const GithubMark = createIcon(19, true);
export const Candle = createIcon(20, true);
export const Mirror = createIcon(21, true);
export const Folder = createIcon(22, true);
export const Lock = createIcon(23, true);
export const Sparkles = WandSparkles;
export const Signpost = Route;
export const Zap = WandSparkles;
export const Refresh = (props: IllustratedIconProps) => <svg width={props.size ?? 24} height={props.size ?? 24} viewBox="0 0 32 32" aria-hidden="true" {...props}><path d="M25 12C20 2 6 5 5 16c-1 10 12 15 20 7" fill="none" stroke="#e6bc6a" strokeWidth="5" strokeLinecap="round"/><path d="m19 12 9 2-1-10" fill="#e6bc6a" stroke="#3c2a18" strokeWidth="2"/></svg>;
export const Close = (props: IllustratedIconProps) => <svg width={props.size ?? 24} height={props.size ?? 24} viewBox="0 0 32 32" aria-hidden="true" {...props}><path d="m7 4 9 9 9-8 4 4-10 9 9 9-5 3-8-9-9 8-4-4 10-9-8-8Z" fill="#e6bc6a" stroke="#3c2a18" strokeWidth="2" strokeLinejoin="round"/></svg>;
export const Skull = ({size=24,...props}: IllustratedIconProps) => <svg width={size} height={size} viewBox="0 0 40 40" aria-hidden="true" {...props}><path d="M7 23C-2 3 36-4 36 18c0 8-7 7-7 11l-1 7-16-1-1-8Z" fill="#f0dfb1" stroke="#3c2a18" strokeWidth="3" strokeLinejoin="round"/><path d="m10 16 8-2-1 8-7-1Zm14-2 8 3-1 6-8-2Zm-4 9-3 5h7Z" fill="#3c2a18"/><path d="M16 30v6m6-5v6" stroke="#3c2a18" strokeWidth="2"/></svg>;
export const Scales = ({size=24,...props}: IllustratedIconProps) => <svg width={size} height={size} viewBox="0 0 40 40" aria-hidden="true" {...props}><path d="m17 4 5-1 2 28 9 5H8l10-5Z" fill="#e6bc6a" stroke="#3c2a18" strokeWidth="2"/><path d="m6 12 27-2M7 12l-5 12m5-12 6 12m19-13-5 12m5-12 6 12" fill="none" stroke="#bc9860" strokeWidth="3"/><path d="M1 24h14c-2 9-11 8-14 0Zm25-1h13c-2 9-11 9-13 0Z" fill="#e6bc6a" stroke="#3c2a18" strokeWidth="2"/></svg>;
const textIcons: Record<string, LucideIcon> = {"🏆":Trophy,"💀":Skull,"⚖":Scales,"🤝":Users,"🤖":Bot,"🎮":Gamepad2,"🔭":Eye,"🏰":Castle,"🔗":Share2,"🧠":Brain,"🌪":Tornado,"✧":WandSparkles,"🎧":Headphones,"🐶":Dog,"→":ChevronRight,"←":ChevronLeft,"⚔":Swords,"✦":WandSparkles,"⚜":Flower,"📷":Camera,"📁":Folder,"⚡":Zap,"🔄":Refresh,"✕":Close,"🔒":Lock,"🕯":Candle,"🪞":Mirror,"🔮":Crystal,"👁":Eye,"💪":BicepsFlexed,"📊":Spreadsheet,"🏠":House,"💸":Coins,"🎭":VenetianMask,"🔧":Wrench,"🍕":Pizza,"🌿":Leaf,"🧹":Broom,"🎤":Headphones,"📈":BarChart3,"❤️":Heart,"❤️‍🔥":Heart,"🛡":Shield,"🐾":Dog,"✨":WandSparkles,"🌀":Tornado,"★":WandSparkles,"✓":Check};
const iconPattern = new RegExp("(" + Object.keys(textIcons).sort((a,b) => b.length-a.length).join("|") + ")\\uFE0F?", "gu");
export function IconText({ text, size = "1.2em" }: { text: string; size?: number | string }) {
  return text.split(iconPattern).filter(Boolean).map((part, i) => { const Icon = textIcons[part.replace(/\uFE0F/g, "")] ?? textIcons[part]; return Icon ? <Icon key={i} size={size} style={{ display: "inline-block" }} /> : part; });
}
